## ===----------------------------------------------------------------------===
## 
## This source file is part of the Discogs Service open source project
## 
## Copyright (c) 2025 Röck+Cöde VoF. and the Discogs Service project authors
## Licensed under Apache license v2.0
## 
## See LICENSE for license information
## See CONTRIBUTORS for the list of Discogs Service project authors
##
## SPDX-License-Identifier: Apache-2.0
## 
## ===----------------------------------------------------------------------===
                    
generate:
    - types
    - client
namingStrategy: idiomatic
accessModifier: public
